advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('<str:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('update/<str:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<str:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={"pk": self.pk})
    

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    School = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView, DetailView, 
                                    CreateView, UpdateView, DeleteView)
from django.urls import reverse_lazy
from django.http import HttpResponse
from . import models

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    template_name = 'basic_app/school_list.html'
    
class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location') # fields must be given
    model = models.School
    template_name = 'basic_app/school_update_form.html'

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal') # fields must be given
    model = models.School
    template_name = 'basic_app/school_update_form.html'

class SchoolDeleteView(DeleteView):
    context_object_name = 'school'
    model = models.School
    template_name = 'basic_app/school_delete.html'
    success_url = reverse_lazy('basic_app:list')

    

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <title>Django CBV</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:create' %}">Create</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block body_block %}
    {% endblock body_block %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
</body>

</html>

advcbv/basic_app/templates/basic_app/school_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<h1>Delete {{school.name}}</h1>
<form method="POST">
{% csrf_token %}
<input type="submit" class="btn btn-danger" value="Delete">
</form>
<a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
{% endblock body_block %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>Welcome to the school detail page.</h1>
<h2>School Detail:</h2>
<p>Name: {{school_detail.name}}</p>
<p>Principal: {{school_detail.principal}}</p>
<p>Location: {{school_detail.location}}</p>
</div>
<h3>Students:</h3>
{% for student in school_detail.students.all %}
<p>{{student.name}} who is {{student.age}} years old.</p>
{% endfor %}
<p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
{% endblock body_block %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<h1>Welcome To School List</h1>
<ol>
{% for school in schools %}
<h2><li><a href="{{school.id}}">{{ school.name }}</a></li></h2>
{% endfor %}
</ol>
{% endblock body_block %}

advcbv/basic_app/templates/basic_app/school_update_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<h1>
{% if not form.instance.pk %}
Create School
{% else %}
Update School
{% endif %}
</h1>
<form method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit" class="btn btn-primary" value="Submit">
</form>
{% endblock body_block %}

advcbv/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <title>Django CBV</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Disabled</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block body_block %}
    {% endblock body_block %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
</body>

</html>

advcbv/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Home Page!</h1>
{% endblock body_block %}